---
- name: hosts.yml
  hosts: all
  tasks:
    - name: Template a file to /etc/file.conf
      ansible.builtin.template:
        src: Myhosts.j2 
        dest: /etc/myhosts
      when: "'dev' in group_names"


