---
- name: issue.yml 
  hosts: all
  tasks:
    - name: Copy using inline content
      ansible.builtin.copy:
        content: 'Development'
        dest: /etc/issue
      when: "'dev' in group_names"

    - name: Copy using inline content
      ansible.builtin.copy:
        content: 'PROD'
        dest: /etc/issue
      when: "'prod' in group_names"

    - name: Copy using inline content
      ansible.builtin.copy:
        content: 'test'
        dest: /etc/issue
      when: "'test' in group_names"


