---
- name: packages.yml
  hosts: dev,test,prod
  tasks:
    - name: Install the php and mariadb
      ansible.builtin.dnf:
        name:
          - php
          - mariadb
        state: present



- name: packages.yml
  hosts: dev
  tasks:
    - name: Install the php and mariadb
      ansible.builtin.dnf:
        name:
          - "@RPM Development tools"
        state: present

    - name: Install the php and mariadb
      ansible.builtin.dnf:
        name:
          - "*"
        state: latest    
